# Tell Travis that we need a copy of docker running
sudo: required
services:
    - docker

# Build out image using Dockerfile.dev
before_install:
    - docker build -t ccanning2/docker-react -f Dockerfile.dev .

# Tell Travis how to run our test suite
script:
    - docker run -e CI=true ccanning2/docker-react npm run test

# Tell Travis how to deploy our code to AWS
deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    environment: "Docker-react-env"
    bucket_name: "elasticbeanstalk-us-east-1-12345"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY


